### ISSUE TITLE
I just upgraded version from 6.4.2 to 6.4.3 and the archive is not working.

### ISSUE THREAD

**Issue by matsuda-argano** [twilio/twilio-voice-ios#100]
When I upgraded my version from 6.4.2 to 6.4.3, the archive did not work, so I was investigating the cause and found a suspicious part in the TwilioVoice.xcframework.

It seemed to me that the version update of the following file was not appropriate, what do you think?
TwilioVoice.xcframework/ios-arm64_x86_64-simulator/dSYMs/TwilioVoice.framework.dSYM/Contents/Info.plist

Please note that I am not a developer specializing in iOS, so my question may be fundamentally wrong.

Translated with www.DeepL.com/Translator (free version)

<img width="945" alt="スクリーンショット 2022-11-18 14 59 16" src="https://user-images.githubusercontent.com/106219284/202632971-f986eff6-a8cb-463c-815d-7d6c8a5aa908.png">

**Comment by bobiechen-twilio** [comment]
@matsuda-argano 
Can you provide the details of the error you encountered? The best practice to integrate or upgrade to the latest version of the SDK will be via the Swift Package Manager.

**Comment by matsuda-argano** [comment]
@bobiechen-twilio 
To be precise, archiving succeeds.
However, it does not appear in the Organizer of Xcode.
If I check Xcode > Archvies in Finder, I can see the .xcarchive file, but when I try to open it in Xcode, I get an error.
<img width="264" alt="スクリーンショット 2022-11-21 8 12 44" src="https://user-images.githubusercontent.com/106219284/202931847-a9d0783d-3614-4872-83f5-cd38d1f05287.png">

Is there anything wrong with the version of the above capture?

I have tried deleting the cache, etc.
Since the problem does not occur in v6.4.2, I am wondering if the upgrade is the problem.
