### ISSUE TITLE
Video Call Audio Not Working

### ISSUE THREAD

**Issue by Harshad290194** [twilio/twilio-voice-ios#107]
Video Call SDK when first time allow for mic then audio works fine but when end call and again call then audio in video call (mic) not working

**Comment by bobiechen-twilio** [comment]
Hi @Harshad290194 

The Voice SDK does not support video and does not guarantee audio when used side by side with video calling. Please reach out to [Twilio Support](https://support.twilio.com/hc/en-us) with the following if you are still having trouble connecting calls:
- Issue description
- Steps to reproduce
- SDK logs
- Twilio Call SID if any

Thanks,
-bobie
