### ISSUE TITLE
iOS SDK Crash after initialization

### ISSUE THREAD

**Issue by blazorin** [twilio/twilio-voice-ios#109]
### Description

The SDK crashes right before starting a call.
This was not happening before.

I have assured all data is not null when passed to the TVOCall object.

### Steps to Reproduce

1. Run
2. initBirdCall ends
3. Crashes

#### Code

```objc
@interface TwilioController : NSObject<TVOCallDelegate>
{
    // Handles both endpoint and call

    TVOCall* twilioCall;
    TVODefaultAudioDevice* twilioAudio;

    bool initiated;
    bool callRunning;
    bool callActive;

    bool micEnabled;
    int micStatus;

    bool playbackRunning;
    bool loudEnabled;
}
@end

@implementation TwilioController

-(void) initBirdCall:(NSDictionary * _Nonnull)data micEnabled:(bool) micEnabledParam isEU:(bool) isEUParam
{
    if (Prankster_Native::nativeInstance == nil) {
        NSLog(@"(initBirdCall) nativeInstance is null.");
        return;
    }

    TwilioVoiceSDK.logLevel = TVOLogLevelError;

    // Edge
    if (isEUParam)
        TwilioVoiceSDK.edge = @"frankfurt";
    else
        TwilioVoiceSDK.edge = @"ashburn";

    // Set audio device before anything else
    if (twilioAudio == nil)
    {
        twilioAudio = [TVODefaultAudioDevice audioDevice];
        TwilioVoiceSDK.audioDevice = twilioAudio;

        [twilioAudio retain];
    }


    // Builder Options
    TVOConnectOptions *connectOptions = [TVOConnectOptions
            optionsWithAccessToken:data[@"token"]

            block:^(TVOConnectOptionsBuilder *builder) {
                    builder.params = @{@"to": data[@"to"]};
            }];


    // Create and connect call
    TVOCall *call = [TwilioVoiceSDK connectWithOptions:connectOptions delegate:self];

    if (call) {twilioCall = call;}
    else {
        NSLog(@"(initBirdCall) Init failed.");
        Q_EMIT Prankster_Native::nativeInstance->endpointFailed();

        return;
    }

    [twilioCall retain];


    // Not needed. Twilio handles this correctly.
    //[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(didSessionRouteChange:) name:AVAudioSessionRouteChangeNotification object:nil];


    // Set mic access
    micEnabled = micEnabledParam;
    if (micEnabled)
         NSLog(@"\n(initBirdCall) [INFO] micEnabled = true\n");


    initiated = playbackRunning = true;


    NSString *versionStr = [NSString stringWithFormat:@"%@", @(TwilioVoiceSDK.version).stringValue];
    Q_EMIT Prankster_Native::nativeInstance->endpointCreated(QString::fromNSString(versionStr));

    NSLog(@"(initBirdCall) Init success.");
}
```

Curiously, time ago I needed to add the retain lines for the call to begin, but this looks different,
the error triggers when the initBirdCall method ends. 

#### Actual Behavior

Function ends and crashes with the error below.

#### Logs

```
(initBirdCall) [INFO] micEnabled = true
2023-02-28 03:33:13.969036+0100 Prankster[648:12830] (initBirdCall) Init success.

2023-02-28 03:33:13.973254+0100 Prankster[648:12830] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[6]'
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

Latest

#### Xcode

14.1

#### iOS Version

16.3.1

#### iOS Device

iPhone SE 2020

**Comment by bobiechen-twilio** [comment]
Hi @blazorin 

Is it possible for you to provide the stack trace when the crash happens? Also does this happen every time?

**Comment by blazorin** [comment]
100% of the times.

![Screenshot 2023-02-28 at 14 40 17](https://user-images.githubusercontent.com/32218025/221870767-8810527c-9381-4a5d-90a9-bcc87796fff3.png)

`Thread#0	0x00000001b48f0e38 in __exceptionPreprocess ()
#1	0x00000001ada8b8d8 in objc_exception_throw ()
#2	0x00000001b4a96078 in _CFThrowFormattedException ()
#3	0x00000001b4aa13ac in -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 ()
#4	0x00000001b490c2b8 in -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] ()
#5	0x00000001b490c158 in +[NSDictionary dictionaryWithObjects:forKeys:count:] ()
#6	0x00000001082da774 in +[TVOEndpointAnalyticsUtilities getPlatformMetadata] at /Users/distiller/project/TwilioVoiceClient/TwilioVoiceClient/Sources/Implementation/Insights/TVOEndpointAnalyticsUtilities.m:41
#7	0x00000001082f57a4 in +[TVOEndpointAnalyticsEvent eventWithName:group:level:payload:] at /Users/distiller/project/TwilioVoiceClient/TwilioVoiceClient/Sources/Implementation/Insights/TVOEndpointAnalyticsEvent.m:150
#8	0x00000001082e4230 in -[TVOEventReceiver publishSignalingStateEvent:] at /Users/distiller/project/TwilioVoiceClient/TwilioVoiceClient/Sources/Implementation/Insights/TVOEventReceiver.mm:270
#9	0x00000001082e6bd4 in twilio::voice::InsightsEventObserverAdapter::onEvent(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, twilio::voice::DataType>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, twilio::voice::DataType> > > >) at /Users/distiller/project/TwilioVoiceClient/TwilioVoiceClient/Sources/Implementation/Voice/InsightsEventObserverAdapter.h:82
#10	0x00000001087153b8 in std::__1::__function::__func<twilio::voice::CallImpl::postEvent(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_50, std::__1::allocator<twilio::voice::CallImpl::postEvent(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_50>, void ()>::operator()() ()
#11	0x00000001067e453c in _dispatch_call_block_and_release ()
#12	0x00000001067e5ff0 in _dispatch_client_callout ()
#13	0x00000001067f6800 in _dispatch_main_queue_drain ()
#14	0x00000001067f6344 in _dispatch_main_queue_callback_4CF ()
#15	0x00000001b49816c8 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#16	0x00000001b496302c in __CFRunLoopRun ()
#17	0x00000001b4967eb0 in CFRunLoopRunSpecific ()
#18	0x00000001eeb5d368 in GSEventRunModal ()
#19	0x00000001b6e5d668 in -[UIApplication _run] ()
#20	0x00000001b6e5d2cc in UIApplicationMain ()
#21	0x0000000101244e98 in qt_main_wrapper ()
#22	0x00000001d3260960 in start ()
`

Same exception name as issue [#94](https://github.com/twilio/twilio-voice-ios/issues/94).

**Comment by bobiechen-twilio** [comment]
Thanks @blazorin 

The SDK checks a few fields in the application's bundle info such as app version, Xcode version etc. From the stacktrace looks like the SDK cannot find `CFBundleName` in the app's plist. Any chance this field or any of the following is empty from the plist? 
```
CFBundleName
CFBundleIdentifier
CFBundleShortVersionString
CFBundleVersion
MinimumOSVersion
DTPlatformVersion
```

**Comment by blazorin** [comment]
@bobiechen-twilio Yes!! You hit on the center of the issue!

The **CFBundleName** on my plist had a variable, which was referencing to nothing, just wrote the app name in there and done.

I appreciate the quick help on this. Now calls work correctly

Best, Alberto.

**Comment by bobiechen-twilio** [comment]
Thanks for confirming the root cause. This is actually a bug in the SDK - we should at least have back-off mechanism if the value is not available. We will address this in the SDK soon.

-bobie
