### ISSUE TITLE
Getting error code 53000 while doing voice call

### ISSUE THREAD

**Issue by dishankEbizz** [twilio/twilio-voice-ios#122]
Hello, Getting below given error from SDK. Can you please check and let me know what's wrong here?
Error: Failed to connect to room with error Error Domain=com.twilio.video Code=53000 "Signaling connection error" UserInfo={NSLocalizedDescription=Signaling connection error, NSLocalizedFailureReason=SIP error 503}

SDK version: **TwilioVoice 5.5.0**

**Comment by bobiechen-twilio** [comment]
Hi @dishankEbizz 

Thanks for reaching out. The 53000 error typically indicates that the SDK is experiencing some sort of network connectivity issue that causes the SDK trouble maintaining the signaling or media connection. The application should receive a callback on the `TVOCallDelegate` indicating that the SDK is trying to reconnect and should momentarily receive another `reconnected` callback. Sometimes the SDK might not be able to reestablish the connection and will eventually raise the `disconnected` callback.
