### ISSUE TITLE
Crash when receiving a call invite while the device is on "Do not disturb"

### ISSUE THREAD

**Issue by nalexn** [twilio/twilio-voice-ios#123]
### Description

This is an actualized crash detail of the issue #120 for the latest SDK 6.10.0

### Steps to Reproduce

1. Run on a device iOS 16+, open the "Focus" menu, and enable "Do not disturb"
2. Call that device
3. Twilio SDK causes a crash

When the incoming call is reported to CallKit by `reportNewIncomingCall`, it calls back with an error `CXErrorCodeIncomingCallError.filteredByDoNotDisturb`. No further calls to the Twilio SDK are made, it crashes shortly after.

#### Crash details

```swift
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x5c491368ac48.

0 TwilioVoice +0xb85d0            rtc::Thread::Get(int)
1 TwilioVoice +0xb7ce0            rtc::Thread::ProcessMessages(int)
2 TwilioVoice +0xb8d5c            rtc::Thread::PreRun(void*)
3 libsystem_pthread.dylib +0x24d0 __pthread_start
```

#### Reproduces How Often

50 crashes per 1000 call invites received while on Do not Disturb. Most of the crashes (98%) happen while the app is backgrounded.

#### Voice iOS SDK

6.10.0 via SPM

#### Xcode

15.2

#### iOS Version

iOS 16, iOS 17

#### iOS Device

Any

**Comment by bobiechen-twilio** [comment]
Thanks for the debugging information. I've opened an internal ticket for tracking and will keep you updated.

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @nalexn 

While I am still trying to reproduce the crash, is it possible for you to try the same "Do not disturb" setup using the [quickstart](https://github.com/twilio/voice-quickstart-ios) (if you haven't) and see if the same crash is happening? Also curious in how the `TVOCallInvite` object is kept in your application - is the ownership retained with some instance variable and is this done before reporting to CallKit?

-bobie

**Comment by nalexn** [comment]
I'm also having hard time reproing in our app, but logs from the crashed devices clearly indicate the use case I described. We have a remote feature flag controlling `TVOCallInvite` deallocation logic - either immediately or after a delay from bg, so far it was using the bg deallocation. I've flipped the flag and will observe if anything changes. I'll keep you updated

**Comment by nalexn** [comment]
I ran the experiment for 15 hours and there was no indication of any improvement.

**Comment by dipankadas** [comment]
@nalexn We have tried reproducing the issue using our quick start and even with multiple attempt, we are unable to repro this crash. We will keep an eye out for the crash in our CI jobs and test jobs.

**Comment by dipankadas** [comment]
Closing this as this is not reproducible and we are not seeing this in our tests. We can reopen if needed
