### ISSUE TITLE
Multiple leaks from TwilioVoice.

### ISSUE THREAD

**Issue by makaveli9727** [twilio/twilio-voice-ios#124]
### Description

There are at least 9 leaks produced by TwilioVoice SDK in our app.
 I already tried profiling a [quickstart](https://github.com/twilio/voice-quickstart-ios) repository and updated TwilioVoice SDK to **v6.10.1** and those leaks persist there as well.
You can replicate the process independently by utilizing **Instruments.app** and conducting a profile analysis on the Quickstart.

### Steps to Reproduce

1. Profile on iOS 15+ versions.
2. After Profiling finish, choose a template "Leaks" and record leaks by pressing "Start an immediate mode recording"
3. **9 leaks appear** right after 5-7 seconds.

#### Providing a screenshot of a recorded .trace file:
![Leaks](https://github.com/twilio/twilio-voice-ios/assets/32404338/c933d39a-0915-42c9-8b6e-a124a843e8a0)

#### Reproduces How Often

100%

#### Voice iOS SDK

v6.10.1 via SPM

#### Xcode

v15.2

#### iOS Version

iOS 15, 16, 17, 17+

#### iOS Device

Any

**Comment by dipankadas** [comment]
@makaveli9727 The leaks are coming from a third party library that we use for SIP signaling. We will see if anything can be done in the third party lib to fix the issue but that might take a while.

**Comment by dipankadas** [comment]
This is not a high priority now. We will take up this work when we upgrade the third party library. Closing this now we will create internal ticket for this issue to track
