### ISSUE TITLE
SDK Jitter Default Settings

### ISSUE THREAD

**Issue by benford-servicem8** [twilio/twilio-voice-ios#126]
Now that the Twilio SDK supports setting `audioJitterBufferMaxPackets` and `audioJitterBufferMinDelayMs`, is there any guidance from Twilio regarding good defaults for devices in the field (eg 4G/5G connections) ?

**Comment by dipankadas** [comment]
@benford-servicem8 If no Audio Option is provided, then the default option is used. The default uses`audioJitterBufferMaxPackets` size of 50 and `audioJitterBufferMinDelayMs` of `0` milliseconds. Unless the users are seeing network issues the default values should be fine. For poor network, Jitter buffer size can be increased to 200 or more. We don't recommend increasing `audioJitterBufferMinDelayMs` without running some experiments in a poor network condition.

**Comment by benford-servicem8** [comment]
Thanks @dipankadas , are you able to confirm if the TwilioSDK would take advantage of the underlying support WebRTC has for Dynamic jitter buffering?

**Comment by dipankadas** [comment]
@benford-servicem8 yes, Twilio SDK would take advantage of dynamic jitter buffer.
