### ISSUE TITLE
Unable to distribute app to store due to bitcode validation in Xcode 16

### ISSUE THREAD

**Issue by bevbomb** [twilio/twilio-voice-ios#131]
### Description

Unable to distribute my app with TwilioVoice installed to store with the following error appearing every time i try.

> **Asset Validation Failed**
> Invalid Executable. The executable 'XXX.app/Frameworks/TwilioVoice.framework/TwilioVoice' contains bitcode.

I have tried installing the package manually, via CocoaPods and via Swift Package Manager. The app builds and runs correctly but since the Xcode update, i can no longer distribute to the store.

### Steps to Reproduce

1. Install the latest TwilioVoice package via CocoaPod and run through the basic setup for TwilioVoice
2. Archive the app app
3. Attempt to distribute to store

#### Expected Behavior

App distributes to store without errors.

#### Actual Behavior

Unable to distribute App to store with Xcode showing errors

#### Reproduces How Often

Every time.

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

6.5.2

#### Xcode

16.0

#### iOS Version

18.0

#### iOS Device

iPhone 15 Pro Max

**Comment by bobiechen-twilio** [comment]
Please use the iOS SDK 6.7.0: [changelog](https://www.twilio.com/docs/voice/sdks/ios/changelog#670)
