### ISSUE TITLE
Build error in 6.12.0: "TVOPreflightReport.h:19:1: imported declaration 'TVOPreflightCallQuality' could not be mapped to 'Preglith.CallQuality'"

### ISSUE THREAD

**Issue by Westacular** [twilio/twilio-voice-ios#133]
### Description

There appears to be a typo in TVOPreflightReport.h in the 6.12.0 release which is causing build failures when using CocoaPods.

Specifically, in that header file, you have:

```
typedef NS_ENUM(NSUInteger, TVOPreflightCallQuality) {
    [...omitted...]
}
NS_SWIFT_NAME(Preglith.CallQuality);
```

and I suspect that `NS_SWIFT_NAME(Preglith.CallQuality)` somehow got mangled and it is supposed to be `NS_SWIFT_NAME(PreflightCallQuality)` ?

### Steps to Reproduce

1. Use CocoaPods to get TwilioVoice 6.12.0
2. Build with Xcode 16.1
3. Build fails in Swift code which has `import TwilioVoice` with:

```
[...]/XCFrameworkIntermediates/TwilioVoice/TwilioVoice.framework/Headers/TVOPreflightReport.h:19:1: imported declaration 'TVOPreflightCallQuality' could not be mapped to 'Preglith.CallQuality'
NS_SWIFT_NAME(Preglith.CallQuality);
^
```

#### Reproduces How Often

Always

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

6.12.0 via CocoaPods

#### Xcode

16.1

**Comment by bobiechen-twilio** [comment]
@Westacular Thanks again for reaching out and reporting the typo. The fix is now available in [6.12.1](https://www.twilio.com/docs/voice/sdks/ios/changelog#6121).
