### ISSUE TITLE
[Warnings] Conflicting return type in TwilioVoice.h via release build

### ISSUE THREAD

**Issue by rob-keepsafe** [twilio/twilio-voice-ios#2]
### Description

When building for release configuration using `xcodebuild`, we're seeing this warning:

>INFO [2018-05-22 14:36:40.90]: ▸ ⚠️  /Users/distiller/project/../../Pods/TwilioVoice/TwilioVoice.framework/Headers/TwilioVoice.h:75:1: conflicting return type in declaration of 'version': 'NSInteger' (aka 'long') vs 'NSString * _Nonnull' [-Woverriding-method-mismatch]
>INFO [2018-05-22 14:36:40.90]: ▸ + (nonnull NSString *)version;

Base declaration from `NSObject` here:

<img width="1215" alt="screen shot 2018-05-23 at 11 12 37 am" src="https://user-images.githubusercontent.com/30269720/40433538-3d5c0ee0-5e7a-11e8-86e2-846ba3c3c357.png">

### Steps to Reproduce

1. Integrate into project using CocoaPods
2. Build with `-configuration Release` using `xcodebuild`

#### Expected Behavior

Return types should match.

#### Actual Behavior

Return types don't match, so warning is shown.

#### Reproduces How Often

Every time.

### Versions

Swift 4

#### Voice iOS SDK

2.0.4 via CocoaPods

#### Xcode

9.3

#### iOS Version

11.3

#### iOS Device

Building via Terminal

**Comment by bchen-twilio** [comment]
Hi @rob-keepsafe 

Thanks for reporting this! We will investigate and provide fix as soon as we can.

**Comment by bchen-twilio** [comment]
Hi @rob-keepsafe 

While we are trying to fix this we realized that this will introduce an API break. We are in fact working on refactoring our core stack and we expect APIs to be updated, so we will make this change in the new version.

For now, will adding the `-Woverriding-method-mismatch` flag considered an acceptable workaround for you?

```
// where the TwilioVoice.version() method is called
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Woverriding-method-mismatch"

...
TwilioVoice.version()

#pragma clang diagnostic pop
```

Sorry for the inconvenience.

Thanks
-bobie

**Comment by rob-keepsafe** [comment]
No worries, that works for us @bchen-twilio ! Thanks!

**Comment by bchen-twilio** [comment]
Thanks @rob-keepsafe !
Really appreciate your understanding and thanks again for reporting this issue.
👍
