### ISSUE TITLE
Carthage doesn't download the prebuilt framework for v5.*

### ISSUE THREAD

**Issue by dkornev** [twilio/twilio-voice-ios#20]
### Description

When you are installing the Twilio Voice v5.0.0 framework using Carthage, it doesn't download the prebuild archived framework.

### Steps to Reproduce

1. Create a new _Cartfile_ file with one line there:
`github "twilio/twilio-voice-ios" == 5.0.0`
2. Run _carthage update_
3. Check generated files in _/Carthage/Build/iOS/_ folder

#### Expected Behavior

_TwilioVoice.framework_ should be downloaded into the generated folder (_/Carthage/Build/iOS/_)

#### Actual Behavior

_TwilioVoice.framework_ is not downloaded into the generated folder (_/Carthage/Build/iOS/_)

#### Reproduces How Often

100%

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

5.0.0 via Carthage

**Comment by bobiechen-twilio** [comment]
Hi @dkornev 

Thanks for reporting the issue.
I have deleted the dSYM file, which might cause some artifact name conflict with the framework when downloading using Carthage.

Please try again.
Sorry for the inconvenience.

-bobie

**Comment by dkornev** [comment]
According to the https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file : 
_... **frameworks should only appear once in the archive** ..._
But for the release v5.0.0, there are two *.framework files attached to the assets

**Comment by dkornev** [comment]
Hi @bchen-twilio 
It was an incredibly quick response!
Thank you, closing this

**Comment by bobiechen-twilio** [comment]
Sure things and thanks again for reporting this. I have created a ticket for addressing the naming issue in future releases.

Cheers,
-bobie

**Comment by dkornev** [comment]
Hi @bchen-twilio 
I see that the same issue is now reproducible with https://github.com/twilio/twilio-voice-ios/releases/tag/5.1.0.
Could you please remove the _**TwilioVoice.framework.dSYM.zip**_ file from the release assets.

**Comment by bobiechen-twilio** [comment]
Hi @dkornev 

Thanks for monitoring the SDK! Just removed the dSYM from the artifact list. Please try again.
Sorry for the inconvenience.

Cheers,
-bobie

**Comment by dkornev** [comment]
Fixed. Closing this

**Comment by dkornev** [comment]
Hi @bchen-twilio

Ha, looks like it happens again :-). Apparently, it's a big one because obviously not many people are using Carthage for the SDK. 
Could you please remove the TwilioVoice.framework.dSYM.zip file again when you have time?

Thank you.

**Comment by bobiechen-twilio** [comment]
Hi @dkornev 

Thanks for reporting the problem.
I was doing some experiments to make sure that the Carthage integration instructions we provide work with the binary file. I was able to use the following line in my `Cartfile` to successfully download the latest framework binary, while the dSYM file can stay side-by-side:
```
binary "https://raw.githubusercontent.com/twilio/twilio-voice-ios/Releases/twilio-voice-ios.json"
```

Can you let me know if this works for you?

Thanks,
-bobie

**Comment by bobiechen-twilio** [comment]
By the way, you will also need to run `carthage update` in order to refresh the dependencies.

**Comment by dkornev** [comment]
I believe it will solve the issue. Thank you
