### ISSUE TITLE
Request: Add support for SPM

### ISSUE THREAD

**Issue by isupremedyou** [twilio/twilio-voice-ios#24]
Now that SPM is baked into Xcode 11, it would be great if you could add support for SPM.

**Comment by bobiechen-twilio** [comment]
Hi @travischapman 

Thanks for reaching out. I've created a ticket to research of adding SPM support for the SDK.

-bobie

**Comment by isupremedyou** [comment]
With Swift 5.3, binary assets will be able to be included with Swift Packages. If that has been cause for delay on creaking a `Package.Swift` file, then this Sept/Oct with Xcode 12 that should be resolved!

**Comment by ryanthon** [comment]
Any updates on SPM support? This would greatly help with development.

**Comment by bobiechen-twilio** [comment]
Hi @ryanthon 

Thanks for reaching out.
We do have plan to upgrade our pipeline to use the latest build tools of Xcode 12 now that it's GA and should also be available from the CI providers. We will keep everyone posted with the progress.

Cheers,
-bobie

**Comment by dmallory** [comment]
We are eager to take advantage of this as well. Thanks!

**Comment by ryanthon** [comment]
Any updates on SPM support?

**Comment by piyushtank** [comment]
No updates other than we plan to start working on xcframework and SPM support in next sprint. We will keep you posted. Thank you!

**Comment by bobiechen-twilio** [comment]
Hi everyone,

We are happy to inform you that we have just released the [Voice iOS SDK 6.2.0](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#620), which is delivered as XCFramework. Please use the [twilio-voice-ios](https://github.com/twilio/twilio-voice-ios) repository and integrate the SDK into your app using the Swift Package Manager.

Cheers,
-bobie

**Comment by lickel** [comment]
Is it possible to vend a Catalyst compatible binary? I realize it won't _do_ anything, but Xcode refuses to compile our app as the slice is missing.
