### ISSUE TITLE
Doesn't  work incoming calls when the application is terminated.

### ISSUE THREAD

**Issue by mroffmix** [twilio/twilio-voice-ios#28]
### Description

Incoming calls don't work when the application is terminated.
**But when the app is on background or foreground mode everything works fine.**
Also, I noticed that methods didReceiveIncomingPushWithPayload and didReceiveIncomingPushWith were not fired. 

But when I open the application after I see the Callkit screen for a few seconds. 
I tried to catch the issue throw debugger. 
####  There is the next behavior:

- Run app from Xcode (Launch option is "Wait for executable to be launched")
- The debugger is waiting for applications launch 
- The call is coming. The app is running in a background 
- didReceiveIncomingPushWithPayload and didReceiveIncomingPushWith not called 
- Nothing more happend 

#### Code

```swift
func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType) {
    NSLog("pushRegistry:didReceiveIncomingPushWithPayload:forType:")
    if (type == PKPushType.voIP) {
        TwilioVoice.handleNotification(payload.dictionaryPayload, delegate: self, delegateQueue: nil)
    }
}

func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
    let data = payload.dictionaryPayload
    print("!!! - didReceiveIncomingPushWith")
    if let twiparams = data[String("twi_params")] as? String {
        if let range = twiparams.range(of: "ActivityId=") {
            let activityId = twiparams[range.upperBound...].prefix(36)
            self.activityId = String(activityId)
        }
        let array = twiparams.split(separator: "&").filter(){$0.contains("Title=")}
        
        if let some = array.first {
            self.from = String(some).replacingOccurrences(of: "+", with: " ").replacingOccurrences(of: "Title=", with: "")
        }
    }
    
    if (type == PKPushType.voIP) {
        TwilioVoice.handleNotification(payload.dictionaryPayload, delegate: self, delegateQueue: nil)
    }
    
    if let version = Float(UIDevice.current.systemVersion), version < 13.0 {
        self.incomingPushCompletionCallback = completion
    } else {
        completion()
    }
}
```

#### Reproduces How Often

Always

#### Voice iOS SDK

TwilioVoice (5.0.0)

#### Xcode

Version 11.2 (11B52)

#### iOS Version

iPadOS 13.2.2 i
ios 13.2.2

#### iOS Device

iPad  6th generation

**Comment by bobiechen-twilio** [comment]
Hi @mroffmix 

Can you please check the device log (from the Console app) and see if the incoming call notification is received when the app is terminated? The SDK should not have different behaviors under different app states and does not have control if the application receives the `didReceiveIncomingPushWithPayload` callback or not.

Please follow the migration guide and make sure that the application always reports incoming VoIP notifications to CallKit to avoid app being terminated or stopping receiving VoIP notification from the system.

Thanks,
-bobie

**Comment by mroffmix** [comment]
I caught the error. When the app is terminated and the call is coming with push notification I see error Message from debugger: **Terminated due to signal 9**
I have no idea how to debug it

**Comment by bobiechen-twilio** [comment]
Hi @mroffmix 

Please use "Wait for executable to be launched" option to debug the issue when app is terminated and waiting to be launched by the notification.

Please make sure your application is reporting every VoIP notification to CallKit to avoid being terminated by the system.

**Comment by bobiechen-twilio** [comment]
Hi @mroffmix 

I am closing this issue since there has been no activities for a while so I assume the issue has been resolved. Please feel free to reopen if you are still experiencing this problem in the app.

Thanks,
bobie

**Comment by roman-kot** [comment]
@bchen-twilio I am experiencing the same issue. I have just checked with the Voice Quickstart iOS example app and it's the same. Killed app is started for a second when it receives incoming push and then it is terminated by iOS immediately. `Message from debugger: Terminated due to signal 9`

**Comment by vaibhavtech1302** [comment]
I am facing same challenge when app is in background or terminated state the call is not coming else in forground state working fine and my iOS version is 13 and above.

**Comment by bobiechen-twilio** [comment]
@vaibhavtech1302 Please make sure your app handles PkPushRegistry object at the frontmost element. [@anas-p](https://github.com/anas-p) shared a their solution: https://github.com/twilio/voice-quickstart-ios/issues/308#issuecomment-807933418

**Comment by vitalii-tym** [comment]
I had this issue when I forgot to add "Privacy - Microphone Usage Description" record in the registry (not in QuickStart, but already in my project).

**Adding the "Privacy - Microphone..." into info.plist** magically **made the `didReceiveIncomingPushWithPayload` to be called** and it started to work correctly when app is in background/terminated.
