### ISSUE TITLE
Multiple incoming call push notifications for the same call

### ISSUE THREAD

**Issue by dougritter** [twilio/twilio-voice-ios#29]
### Description

When inbound calls are started, multiple push notifications are sent to the same device with the same payload.
As already known, in iOS 13, it's necessary to report all incoming calls to CallKit when VoIP push notifications are received.
When a device receives multiple incomingCalls, it may cause the app to be killed by the system because of the many VoIP pushes to be handled and reported to CallKit.

### Steps to Reproduce

1. Start an inbound call
2. Check the push notifications received by the device
3. Same payload is sent more than one time, changing only the `timestamp` value by some milliseconds.

In our use case, we usually start calls for many devices at the same time. Not all devices receive multiple notifications, but the ones on iOS 13 that receive them cause problems related to the reporting of the incoming call to CallKit.

#### Expected Behavior

Receive only one VoIP push for incoming call

#### Actual Behavior

We receive more than one push notification

#### Reproduces How Often

Around 25%

### Versions

iOS 13.x.x

#### Voice iOS SDK

Not relevant as it is received by APNs, but we use version 5 of the Voice SDK.

#### Xcode

Not relevant as it is received by APNs, but we use XCode 11.2.1

#### iOS Version

13

#### iOS Device

iPhone 7 Plus

**Comment by idelgado** [comment]
@dougritter we recently resolved an issue that could have sent more than one notification for a very small percentage of incoming calls. This was deployed on Saturday.

Have you observed any multiple notifications in the last 48 hours? If so, can you provide the Call SID or the `identity` of the callee.

**Comment by dougritter** [comment]
Hi @idelgado thank you for the information, but the issue was identified today.
The Call Sid is `CA1fff76da2bfb9b841cb01004460c5dbd`
The timestamps:
"2019-11-19 12:22:41.113"
"2019-11-19 12:22:41.138"
"2019-11-19 12:22:41.127"

**Comment by idelgado** [comment]
Our system logs show that we sent a single request to the APNS push gateway for this call. We're reaching out to Apple and continuing to investigate in the meantime.

**Comment by dougritter** [comment]
Oh, that's interesting. Please let us know if you have some feedback from them. Thanks

**Comment by pragmapilot** [comment]
@idelgado Any news about this issue? 

cc @dougritter

**Comment by bchen-twilio** [comment]
Hi @dougritter @pragmapilot 

Just want to check in and see if you are still observing this issue.
We have deployed a server side fix to ensure that potential duplicate bindings are detected and removed so that the mobile clients won't receive multiple notifications for the same call.

We are keeping an eye on the traffic and Insights data in the meantime please let us know how it goes.

Cheers,
-bobie

**Comment by idelgado** [comment]
We reached out to Apple but did not get conclusive evidence from them to indicate what was going on. We have seen cases where customers are failing to initialize the `PkPushRegistry` which can result in several notifications being raised back-to-back once initialized.

We added some more information related to this in the migration guides under step 2: https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#migration-guides

**Comment by bobiechen-twilio** [comment]
Hi @dougritter @pragmapilot 

Hope things are going well. We haven't seen any signs indicating multiple push notifications being received on the callee clients under your account but would like to confirm if you are not still seeing the original issue in your environment.

Please feel free to let us know if you need further assistance.

Cheers,
-bobie

**Comment by tsanto** [comment]
Hi @bchen-twilio 

We may have found the problem. We are still monitoring if the issue was fixed and for that reason we will get back to you in a week or so.

Thanks in advance!

**Comment by bobiechen-twilio** [comment]
Thanks for the update @tsanto.

**Comment by tsanto** [comment]
Hi @bchen-twilio 

The issue was fixed. Thank you!
