### ISSUE TITLE
TVOCall.disconnect has no effect in AppDelegate.applicationWillTerminate

### ISSUE THREAD

**Issue by cnadeau** [twilio/twilio-voice-ios#30]
### Description

Calling TVCCall.disconnect() on the active call in AppDelegate.applicationWillTerminate call does not disconnect the call

### Steps to Reproduce

Using the sample app
- call a phone number
- wait for the phone to ring
- answer the call or not
- kill the app  => the call is still ringing or ongoing if answered

#### Code

```swift
guard let call = self.activeCall else {
      // No active call while calling hangUp???
  return
}

self.performEndCallAction(callUuid: call.uuid, phoneNumber: self.calleePhoneNumber ?? "NO PHONE #???")

call.disconnect()
```

#### Expected Behavior

The rest call should be performed from the SDK to disconnect the call
(probably using the REST API https://www.twilio.com/docs/voice/api/call-resource?code-sample=code-update-a-call-resource-to-end-the-call&code-language=curl&code-sdk-version=json) 

#### Actual Behavior

My guess is that the REST call is dispatched and not executed in a sync call

#### Reproduces How Often

100%

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

4.x (actually a crash occurs in the logger)
5.x (no crash but the call is not disconnected properly)

#### Xcode

10.3.1

#### iOS Version

12.4.1

#### iOS Device

iPad *

**Comment by bobiechen-twilio** [comment]
Hi @cnadeau 

Thanks for reaching out. This is currently a known issue in our SDK and we are actively investigating how to send out the disconnect message to the Twilio service before the app is completely terminated.

-bobie

**Comment by SushanDristi** [comment]
Is there any way we can disconnect Twilio voice call when app is terminated.
