### ISSUE TITLE
callInviteCancelled delegate method in 5.0

### ISSUE THREAD

**Issue by aryo** [twilio/twilio-voice-ios#31]
### Description

In the changelog for 5.0.0, it says

> - [TVONotificationDelegate cancelledCallInviteReceived:] is now [TVONotificationDelegate cancelledCallInviteReceived:error:]
> - The error indicates that the call was canceled as a result of an error. **If no error occurred the error will be nil**

But in the header file for TVONotificationDelegate, the method signature is:
```
- (void)cancelledCallInviteReceived:(nonnull TVOCancelledCallInvite *)cancelledCallInvite error:(nonnull NSError *)error;
```
which suggests that error should be nonnull.

Is this right?

**Comment by piyushtank** [comment]
@aryo Thanks for reaching out. We had documentation error in the [5.0.0 changelogs](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#500) which we just updated. 

Best,
Piyush

**Comment by piyushtank** [comment]
@aryo Closing the ticket as we have updated the changelogs. Feel free to reopen if you find an issue.
