### ISSUE TITLE
Voice SDK 4.x & 5.x: Module 'TwilioVoice' not found

### ISSUE THREAD

**Issue by fmonsalvo** [twilio/twilio-voice-ios#34]
### Description

I have a react-native application and we've built a module using twilio voice 2.x. I'm in the process of upgrading it to 5.x.
I've been able to upgrade to 3.x but, when I use twilio voice 4.x or above via cocoapods I get an error saying `Module 'TwilioVoice' not found`.
Has something changed in the pod structure? I'm not being able to build my application.
I've read the migration guides and searched over the issues but I could not find anything.

### Steps to Reproduce

1. Start with an iOS application using voice SDK 2.x
2. Migrate to 3.x
3. Change Twilio voice version to 4.x or above in the Podfile.
4. run `pod install`
5. Compile.

#### Code

```
#import "RNTwilioVoice.h"
#import <React/RCTLog.h>

@import AVFoundation;
@import PushKit;
@import CallKit;
@import TwilioVoice;

@interface RNTwilioVoice () <PKPushRegistryDelegate, TVONotificationDelegate, TVOCallDelegate, CXProviderDelegate>
@property (nonatomic, strong) NSString *deviceTokenString;
...
```

#### Expected Behavior

The project builds using the same code structure

#### Actual Behavior

The project does not compile with a `Module 'TwilioVoice' not found`

#### Reproduces How Often

Every time.

### Versions

Voice iOS SDK 4.x and above.

#### Voice iOS SDK

4.0.0, 4.3.0, 5.0.0, 5.1.0 via cocoapods

#### Xcode

xCode 11.1

#### iOS Version

Any

#### iOS Device

Any, it does not compile.

**Comment by bobiechen-twilio** [comment]
Hi @fmonsalvo 

Please note that the path of the framework packaging has been updated to `Build/iOS/TwilioVoice.framework` since `4.0.0`. Please check out the [latest podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/f/1/9/TwilioVoice/5.1.0/TwilioVoice.podspec.json) and update the path settings in your existing app project.

Thanks,
-bobie

**Comment by fmonsalvo** [comment]
Hi @bchen-twilio that was the issue!
Thanks, I'll close the issue now.
