### ISSUE TITLE
TVOCall.disconnect() doesn't hang up remote call leg

### ISSUE THREAD

**Issue by markathomas** [twilio/twilio-voice-ios#36]
### Description
Calling TVOCall.disconnect() inside of `public func provider(_ provider: CXProvider, perform action: CXEndCallAction)` disconnects the local leg but leaves the remote leg still active.

### Steps to Reproduce

1. Dial a number on local phone
2. Answer call on remote phone
3. Hangup on local phone

#### Code

```swift
public func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
            NSLog("provider:performEndCallAction:")

            audioDevice.isEnabled = true

            if (self.call != nil) {
                NSLog("provider:performEndCallAction: disconnecting call")
                self.call?.disconnect()
                self.callInvite = nil
                self.call = nil
                action.fulfill()
                return
            }

            if (self.callInvite != nil) {
                NSLog("provider:performEndCallAction: rejecting call")
                self.callInvite?.reject()
                self.callInvite = nil
                self.call = nil
                action.fulfill()
                return
            }
        }
```

#### Expected Behavior

Both legs are terminated

#### Actual Behavior

Local leg is terminated while remote leg is left open

#### Reproduces How Often

100%

#### Logs

XCode logs 
```
provider:performEndCallAction
provider:performEndCallAction: disconnecting call
```

### Versions

5.1.1

#### Voice iOS SDK

5.1.1 via CocoaPods

#### Xcode

11.3

#### iOS Version

13.3

#### iOS Device

iPhone X - local
Android LG G6 - remote

**Comment by markathomas** [comment]
What I'm seeing is when the local leg is disconnected the webhook is never fired to my server that releases the call.  Only after I disconnect the remote call leg is the webhook fired.  As initiator of the call I would expect the webhook to be fired when I disconnect as this is not a conference.

**Comment by bobiechen-twilio** [comment]
Hi @markathomas 

Thanks for reporting the issue and the result does sound odd.
Can you provide a Call SID where this happened? We will need to investigate the log of the signaling connection when the `.disconnect()` happened.

By the way, was the app in the foreground, background or was the device locked when the local client disconnected the call?

Cheers,
-bobie

**Comment by markathomas** [comment]
Hi Bobbie, thanks for looking into this.  One call SID in question is CA95c504b1efa18d9854c84246f3b08d77.  The app was in the foreground on disconnect.  If it makes a difference this was a client to client call.  The Voice SDK called my TwiML app which hit my  server which then dialed a Client directly.  The second leg was created as a child call of the above referenced call SID.  That SID is CA5f8c1049625dfa597047594b946d903b.  Let me know how I may help,

**Comment by bobiechen-twilio** [comment]
Thanks for providing the Call SIDs @markathomas!
I just tried the Swift quickstart and made some client-to-client calls, but I was able to get the remote client disconnected properly. I'll take a look at the SIDs and let you know.

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @markathomas 

I've checked the Call SID and it seems that the second part of the TwiML responses (returned by the `action` URL of the first part) is causing this issue. I'll need to do some local experiments and also reach out to the TwiML experts and see if they can spot anything immediately.

-bobie

**Comment by markathomas** [comment]
OK, thank you Bobie.  It's important to note that from what I saw the TwiML never gets executed until the remote side manually hangs up.  I tested this by looking at the request inspector after hanging up on the local leg and nothing was present in the inspector.  Additionally, I tailed my server logs and did not see the webhook to the release endpoint triggered until after the remote leg manually hung up.

**Comment by bobiechen-twilio** [comment]
I talked to some Voice experts and confirmed the behavior you described - `action` won't be triggered until the call has ended, on both sides of the call legs. The question is why didn't the `disconnect` reach the remote party, which we are trying to figure out and will keep you updated.

-bobie

**Comment by bobiechen-twilio** [comment]
Hi @markathomas 

With some further investigation we found that there was never a disconnect sent out from the caller client. Can you check if there is any error along the path of ending the call? e.g. when requesting the end call action to the CallKit controller. We are trying to make sure that `[TVOCall disconnect]` is called and the signaling event is sent out from the mobile client.

SDK logs would also be great at this moment.

Thanks,
-bobie

**Comment by markathomas** [comment]
Thanks, I don't have logs right now as I am developing this on a remote Mac. I did read in the API docs that if `TVOCall.state == .disconnected` calling disconnect will have no effect,  Could it be that call kit is terminating the connection and disconnecting the call with Twilio?  I am only calling disconnect in one place in the code as such:
```
         if (self.call != nil) {
                NSLog("provider:performEndCallAction: disconnecting call")
                self.call?.disconnect()
                self.callInvite = nil
                self.call = nil
                action.fulfill()
                return
            }
```
and this is inside
```
public func provider(_ provider: CXProvider, perform action: CXEndCallAction)
```
Or, is it possible there a race condition betwen
```
public func call(_ call: TVOCall, didDisconnectWithError error: Error?)
```
and 
```
public func provider(_ provider: CXProvider, perform action: CXEndCallAction)
```
as the former sets to active call to `nil`,

You also can look at the full source code of the app if you want.  It's a flutter plugin integrating TwilioVoice.  The code is on Github at https://github.com/markathomas/flutter_twilio_voice - word of caution;  I am not a Swift developer so be kind!

**Comment by markathomas** [comment]
Bobie, I'm curious, which quickstart did you use?  I have noticed differences between https://github.com/twilio/voice-quickstart-ios and https://github.com/twilio/voice-callkit-quickstart-swift with regards to when `disconnect()` is invoked

**Comment by markathomas** [comment]
Bobie, I've tried the following to no avail:

1. Only calling TVOCall.disconnect() - this leaves both legs open
2. Invoking TVOCall.disconnect() before sending callkit end call tx - this eventually closes both legs  but only due to a timeout in callkit
3. Invoking TVOCall.disconnect() directly after sending callkit end call tx instead of waiting on event from callkit - this has same effect as number 2

As of now I'm at a loss as nothing seems to close both legs and properly end the call via callkit as required by Apple

**Comment by bobiechen-twilio** [comment]
Thanks for the updates of your investigation!

The `voice-callkit-quickstart-swift` was deprecated and no longer maintained. `voice-quickstart-ios` should be the source of truth now.

The flow of disconnecting a call (with CallKit) should be:
1. Initiate the disconnect sequence by requesting a `CXEndCallAction` to the CallKit controller [[code]](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L126)
2. The call controller will let you know if the transaction is successful [[code]](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L641)
3. The application will receive the provider callback if the transaction is successful, then either reject the pending call invite or disconnect the call by calling the SDK methods [[code]](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/ViewController.swift#L553)

Based on what we observed from the Call SID you provided, it's very likely that `call.disconnect()` was not called (something went wrong when requesting the end call transaction to CallKit) or the disconnect request was not sent out before the TVOCall object was killed. Can you try removing the lines where the call and call invite objects are nil'd? That should only be necessary when the `call:didDisconnectWithError:` callback is received, which means the call has been disconnected properly.

Let me know if this helps.

-bobie

**Comment by markathomas** [comment]
Thanks Bobie for the explanation and suggestion.  I'll try it out immediately.

**Comment by markathomas** [comment]
That worked!  I suppose this was pure ignorance on the Swift object lifecycle and how TVOCall.disconnect works.  Thanks so much!
