### ISSUE TITLE
SDK crash calling TwilioVoice calls:params:delegate

### ISSUE THREAD

**Issue by jonburs** [twilio/twilio-voice-ios#4]
### Description

Attempting to make an outgoing call resulted in the application crashing:

Crashed: com.twilio.TVOCommandHandler.commandQ
EXC_BREAKPOINT 0x000000000000defe

Full stack trace is in the "logs" section below

### Steps to Reproduce

We've only seen the crash once, as captured via Crashlytics.

#### Code

```swift
    func connectToClient(_ pending: PendingCall) {
        NSLog("Connecting to twilio client: %@", pending.clientCommId)
        if let at = self.accessToken {
            TwilioVoice.isAudioEnabled = false
            AudioManager.configureVoiceChatAudioSession(defaultToSpeaker: false)

            let twilioState = TwilioCallState(callManager: self, callState: pending.callState)

            let params = ["to": pending.clientCommId]
            let call = TwilioVoice.call(at, params: params, delegate: twilioState)
            twilioState.assignCall(call)
        } else {
            NSLog("Connection request received prior to access token arrival; storing for later")
            pendingCall = pending
        }
    }
```

#### Expected Behavior
The call connects to the specified client

#### Actual Behavior

The application crashed -- see stacktrace below

#### Reproduces How Often

Only once so far, but these kinds of crashes are a very serious problem for our application as even a single one impacts multiple customers

#### Logs

This happened on a customer device so we don't have full logs, just the captured stacktrace

```
Crashed: com.twilio.TVOCommandHandler.commandQ
0  libdispatch.dylib              0x1c580c68 _dispatch_barrier_sync_f_slow + 517
1  TwilioVoice                    0xc43613 -[Twilio addUserAccount:password:host:withParams:] + 366
2  TwilioVoice                    0xc43613 -[Twilio addUserAccount:password:host:withParams:] + 366
3  TwilioVoice                    0xc41c39 -[Twilio createUserAccountWithParams:] + 388
4  TwilioVoice                    0xc41e23 __38-[Twilio createUserAccountWithParams:]_block_invoke + 46
5  libdispatch.dylib              0x1c571783 _dispatch_client_callout + 22
6  libdispatch.dylib              0x1c57da35 _dispatch_barrier_sync_f_invoke + 50
7  TwilioVoice                    0xc3460f +[TVODispatchQueue dispatchSyncOnQueue:withBlock:] + 130
8  TwilioVoice                    0xc41d1d -[Twilio createUserAccountWithParams:] + 616
9  TwilioVoice                    0xc485ad +[TwilioVoice createUserAccountIfNeeded] + 528
10 TwilioVoice                    0xc46d87 +[TwilioVoice call:params:uuid:delegate:] + 446
11 TwilioVoice                    0xc46b39 +[TwilioVoice call:params:delegate:] + 184
12 <OurApp>              0xdfad4 specialized TwilioCallManager.connectToClient(_:) (TwilioCallManager.swift:84)
```

#### Voice iOS SDK

2.0.4 via Cocoapods

#### Xcode

9.3

#### iOS Version

10.3.3

#### iOS Device

iPhone 5

**Comment by bchen-twilio** [comment]
Hi @jonburs 

Thanks for reporting the issue and providing the stack trace.

Although the steps seem to be straightforward, it would still be great if you can provide SDK log (`.verbose) if you manage to reproduce the crash with your application, in case we might have missed some cases in our quickstart sample apps and internal testapp. Once we have more info of how to repro then we have more confidence fixing the crash.

We are sorry for the inconvenience and we are actively working on the new version of the SDK which would no longer suffer from this dispatch queue crash.

cheers,
-bobie

**Comment by jonburs** [comment]
Thanks Bobie. I'll add a log if I'm able to reproduce locally, and am looking forward to the SDK update.

**Comment by bchen-twilio** [comment]
TYVM! @jonburs

**Comment by bobiechen-twilio** [comment]
Closing ticket since there has been no activities for a while. Please feel free to reopen if you are still seeing the problem using the SDK.

Thanks,
bobie
