### ISSUE TITLE
Twilio Voice iOS 13 Migration Issue

### ISSUE THREAD

**Issue by n-nitchevski** [twilio/twilio-voice-ios#45]
### Description

I'm building React Native mobile app using twilio sdk.
It was working fine but after using XCode 11, App crashed when receiving an incoming call in background status.
I followed the migration guide.

#### Code

React Native with Objective C SDK.

I called this in didFinishLaunchingWithOptions

`- (void)fetchAccessToken {
    NSString *kIdentity = [[NSUserDefaults standardUserDefaults] stringForKey:@"kIdentity"];
    NSString *accessTokenEndpointWithIdentity = [NSString stringWithFormat:@"%@?identity=%@", kAccessTokenEndpoint, [kIdentity length] == 0 ? @"testidentity" :kIdentity];
    NSString *accessTokenURLString = [kYourServerBaseURLString stringByAppendingString:accessTokenEndpointWithIdentity];

    NSString *accessToken = [NSString stringWithContentsOfURL:[NSURL URLWithString:accessTokenURLString]
                                                     encoding:NSUTF8StringEncoding
                                                        error:nil];
    if (![self checkRecordPermission]) {
        [self requestRecordPermission:^(BOOL granted) {
            if (granted) {
                [self registerForCallInvite];
                [self configureCallKit];
                self->_accessToken = accessToken;
            }
        }];
    } else {
        [self registerForCallInvite];
        [self configureCallKit];
        _accessToken = accessToken;
    }
}`

And here's how I implemented the migration part.
`

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void(^)(void))completion
{
//    if ([payload.dictionaryPayload[@"twi_message_type"] isEqualToString:@"twilio.voice.cancel"]) {
    if ([type isEqualToString:PKPushTypeVoIP]) {
        CXHandle *callHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:@"alice"];

        CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
        callUpdate.remoteHandle = callHandle;
        callUpdate.supportsDTMF = YES;
        callUpdate.supportsHolding = YES;
        callUpdate.supportsGrouping = NO;
        callUpdate.supportsUngrouping = NO;
        callUpdate.hasVideo = NO;

        NSUUID *uuid = [NSUUID UUID];

        [self.callKitProvider reportNewIncomingCallWithUUID:uuid update:callUpdate completion:^(NSError *error) {

        }];
        dispatch_time_t delay = dispatch_time(DISPATCH_TIME_NOW, NSEC_PER_SEC * 0.5);
        dispatch_after(delay, dispatch_get_main_queue(), ^(void){
            CXEndCallAction *endCallAction = [[CXEndCallAction alloc] initWithCallUUID:uuid];
            CXTransaction *transaction = [[CXTransaction alloc] initWithAction:endCallAction];

            [self.callKitCallController requestTransaction:transaction completion:^(NSError *error) {
            }];
        });
    }
    
    
    if ([type isEqualToString:PKPushTypeVoIP]) {
        [TwilioVoice handleNotification:payload.dictionaryPayload delegate:self delegateQueue:nil];
        if ([[NSProcessInfo processInfo] operatingSystemVersion].majorVersion >= 13) {
            completion();
        }
    }
}
`

#### Expected Behavior

No crashes

#### Actual Behavior

App crashed.

#### Reproduces How Often

All times.

#### Logs

Fatal Exception: NSInternalInconsistencyException
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

5.3.0 via CocoaPods

#### Xcode

11.3.1

#### iOS Version

13.3.1

#### iOS Device

All kinds of iPhones.

**Comment by bobiechen-twilio** [comment]
Hi @n-nitchevski 

This seems to be an issue with RN, but can you use the debugger and see if you are able to receive the `didReceiveIncomingPushWithPayload` callback when the app is in the background or terminated?
Also to simply things, in the callback you just need to keep the following if your mobile client is register with the 5.0 SDK:
```
  if ([type isEqualToString:PKPushTypeVoIP]) {
      if (![TwilioVoice handleNotification:payload.dictionaryPayload delegate:self delegateQueue:nil]) {
          NSLog(@"This is not a valid Twilio Voice notification.");
      }
      completion();
  }
```

**Comment by bobiechen-twilio** [comment]
Hi @n-nitchevski 

Hope things are well.
We haven't heard back from you for a while, but hopefully you have figured out and resolved the issue. I am going to close this ticket but please feel free to reach out when you run into any problem.

Thanks,
bobie
