### ISSUE TITLE
"Empty Credentials" while initiating a call from iOS

### ISSUE THREAD

**Issue by yatindma** [twilio/twilio-voice-ios#46]
I am trying to initiate a call from iOS then it's connecting for 2-3 sec and getting disconnected after that and in Twilio debugger we are getting "Empty Credentials", do you have nay idea regarding the same.

**Comment by bobiechen-twilio** [comment]
Hi @yatindma 

I will close this one and let's continue the discussion in https://github.com/twilio/voice-quickstart-ios/issues/342.
