### ISSUE TITLE
5.4.0 podspec exists in CocoaPods trunk, but the corresponding .zip doesn't

### ISSUE THREAD

**Issue by Westacular** [twilio/twilio-voice-ios#48]
### Description

The latest version in the CocoaPods trunk is showing as 5.4.0, published on May 5: https://github.com/CocoaPods/Specs/blob/master/Specs/f/1/9/TwilioVoice/5.4.0/TwilioVoice.podspec.json

However:

- https://github.com/twilio/twilio-voice-ios/releases/download/5.4.0/TwilioVoice.framework.zip doesn't exist, so `pod update` or `pod install` with that version fail
- there are no release notes here to indicate a 5.4.0 release has occurred

... so I'm guessing something got mixed up, and you need to unpublish this 5.4.0 version in CocoaPods?

**Comment by bobiechen-twilio** [comment]
Hi @Westacular 

Thanks for reporting the issue.

There was a slight change of plans for the 5.4.0 release therefore we have to wait for a couple of days. I have updated the podspec and now it should be pointing to the previous public release (5.3.1).

Sorry for the inconvenience and thanks again for filing the issue.

**Comment by Westacular** [comment]
Thanks for the prompt response!
