### ISSUE TITLE
Incoming call lands on same device when user types are switched

### ISSUE THREAD

**Issue by aksthelion** [twilio/twilio-voice-ios#49]
I'm facing a weird problem since long time and I can't figure it out. I've two types of users. Only one type of users can initiate a call, other user types only receive call.

If I switch the user types on two phones and initiate voice call, call lands on same phone where I was previously logged in as receiver user type.

I call unregister when user logs out so it should clear the token if it's a token issue?

`TwilioVoice.unregister(withAccessToken: twilioToken, deviceToken: deviceTokenString) { (error) in
`

Can anyone help in fixing this issue as it's driving me nuts.
Thanks

**Comment by bobiechen-twilio** [comment]
Hi @aksthelion 

Yes, using the `TwilioVoice.unregister()` method will delete the push notification binding of the mobile client so that it won't receive incoming call push anymore. Unless explicitly unregistered, the push binding stays alive for one year, or until the VoIP certificate has been revoked or expired.

Hope this answer your question.

**Comment by aksthelion** [comment]
I'm still not able to resolve the issue. Calling 'TwilioVoice.unregister()' doesn't have any effect on my issue. Calls are still landing on other device. 

How do we verify that a client is unregistered? Can we check in Twilio dashboard?

Could there be another issue than unregister?

**Comment by bobiechen-twilio** [comment]
Hi @aksthelion 

The `TwilioVoice.unregister()` method should do the job unless the Push Credential SID or the PushKit device token do not match. Please also check if the device token matches the one used in registration.

Please note that the device token is case-sensitive.

Please provide your Twilio Call SID if you believe you are receiving incoming call notifications on a mobile client that should have been unregistered from pushes.

Thanks.

**Comment by aksthelion** [comment]
Here is one SID ISd36082be95e8c50a55226dfea8d45e29 It is coming on device on which I'm not even logged in in the app. Can you please trace it and let me know what I'm doing wrong?

**Comment by bobiechen-twilio** [comment]
Hi @aksthelion 

The `ISxxx` SID is the service ID for the Notify service, which is different from the VoIP service used in the Voice iOS SDK. Please use the Notify SDK to unregister from the push notifications.

**Comment by aksthelion** [comment]
Thanks, I'll check it out.
