### ISSUE TITLE
Can't integrate twilio using carthage

### ISSUE THREAD

**Issue by qaysdwekat** [twilio/twilio-voice-ios#5]
### Description

I'm trying to integrate twilio to my app using carthage 

### Steps to Reproduce

1. add `github "twilio/twilio-voice-ios"` to your cartfile
2. run `carthage bootstrap --platform iOS --cache-builds`

#### Expected Behavior

framework download normally 

#### Actual Behavior
```
*** Downloading twilio-voice-ios.framework binary at "Releasing Twilio Voice SDK iOS 2.0.5"
*** Skipped building twilio-voice-ios due to the error:
Dependency "twilio-voice-ios" has no shared framework schemes for any of the platforms: iOS
```

#### Voice iOS SDK

2.0.5 via Carthage version 0.29.0

#### Xcode

9.4.1

**Comment by bchen-twilio** [comment]
Hi @qaysdwekat 

I tried quickly with both `2.0.5` and `2.0.6` and was able to download the framework correctly. I've also found ([this thread](https://stackoverflow.com/questions/35054788/carthage-no-shared-framework-schemes-for-ios-platform-for-my-own-framework)) that this seems to be a common issue for application developers integrating libraries using Carthage.

Let me know if this helps.
-bobie

**Comment by joeydong** [comment]
i'm also experiencing the same issue when using the `--no-use-binaries` flag in the `carthage install --platform iOS --no-use-binaries`.

here's how it was solved for twilio-chat-ios: https://github.com/twilio/twilio-chat-ios/issues/1

**Comment by joeydong** [comment]
I suppose I could host a file like this myself and update it whenever there is a new release: https://github.com/twilio/twilio-chat-ios/blob/master/twilio-chat-ios.json

**Comment by bobiechen-twilio** [comment]
Hi @joeydong @qaysdwekat 

Thanks for reporting the issue. We have updated the `Releases` branch with the artifact JSON.
Sorry for the inconvenience.

Cheers,
-bobie
