### ISSUE TITLE
Please include dSYM in the framework zip pulled by CocoaPods

### ISSUE THREAD

**Issue by dekpient** [twilio/twilio-voice-ios#52]
### Description

Framework's dSYM is **not** included in CocoaPods package – unlike TwilioSyncClient or TwilioChatClient.

### Steps to Reproduce

1. Add TwilioVoice to Podfile and run pod install
2. Build the app and expect TwilioVoice crashes to have unobfuscated stack trace

#### Expected Behavior

dSYM missing in the package pulled by the Podspec e.g. https://github.com/CocoaPods/Specs/blob/master/Specs/f/1/9/TwilioVoice/5.4.0/TwilioVoice.podspec.json#L18

#### Actual Behavior

dSYM should be included in the zip just like TwilioSyncClient or TwilioChatClient.

These are screenshots from the packages I downloaded via the link in their respective podspecs.

 
<img width="269" alt="twilio-chat" src="https://user-images.githubusercontent.com/717270/84551842-f65e5900-ad62-11ea-9f6c-588de04d01b6.png">
<img width="269" alt="twilio-voice" src="https://user-images.githubusercontent.com/717270/84551845-f8c0b300-ad62-11ea-853e-c41c0772391c.png">
<img width="298" alt="twilio-sync" src="https://user-images.githubusercontent.com/717270/84551847-f9594980-ad62-11ea-9b7a-567bee4629db.png">

#### Reproduces How Often

Every release

### Question

I'm aware of the link to manually download the dSYM on [the release page](https://github.com/twilio/twilio-voice-ios/releases), but it should be included in the package.

Is this something that will be fixed? If not, why? and what's the recommended way to include dSYM when pulling TwilioVoice via CocoaPods?

Cheers!

**Comment by bobiechen-twilio** [comment]
Hi @dekpient 

Thanks for bringing up this great topic. We have created tickets for tracking the progress for debug symbols. We will keep you updated.

**Comment by bobiechen-twilio** [comment]
Hi @dekpient 

We are happy to inform you that we have just released the [Voice iOS SDK 6.2.0](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#620), which is delivered as XCFramework, along with the bitcode and debug symbols. Please use the [twilio-voice-ios](https://github.com/twilio/twilio-voice-ios) repository and integrate the SDK into your app using the Swift Package Manager.

Cheers,
-bobie
