### ISSUE TITLE
Will there be an official React Native sdk?

### ISSUE THREAD

**Issue by liemdo** [twilio/twilio-voice-ios#54]
I see some official examples for Twilio Chat in React Native. Will we have the React Native sdk for voice by any chance soon?

**Comment by idelgado** [comment]
At the moment, we do not have plans to add an official React Native SDK. We will update this ticket if that changes in the future.

**Comment by liyamahendra** [comment]
I created a TwilioVoice React native Bridge for a client of mine. @idelgado I understand you might be having in-house development team, but let me know if I can help. Happy to collaborate!

**Comment by hawkinbj** [comment]
For anyone who might find this thread - I'm the Product lead for the group that builds/maintains the Voice SDKs, and we're actively working on an official Voice React Native SDK for release this year (2022). We're on track to have a Pilot available by late August - please reach out to me if you're interested in testing and/or providing feedback. brhawkins@twilio.com

**Comment by liemdo** [comment]
@hawkinbj This is an incredible news for Twilio customers. I just sent you an email to participate in the program.

**Comment by liyamahendra** [comment]
@hawkinbj just checking on this - is the React native SDK ready or its still being worked on?

**Comment by hawkinbj** [comment]
@liyamahendra thanks for checking back in. We recently released our React Native SDK in Pilot, aiming for Public Beta later this year. [Check it out here](https://github.com/twilio/twilio-voice-react-native), and be sure to read the warnings in the README re: Pilot release support expectations. Would love to hear your feedback on how we can improve (brhawkins@twilio.com)

cc: @liemdo https://github.com/twilio/twilio-voice-react-native
