### ISSUE TITLE
iOS 14

### ISSUE THREAD

**Issue by piyushtank** [twilio/twilio-voice-ios#56]
Ahoy!

Apple has now released iOS 14. To ensure that your application is ready for iOS 14 we are providing the following guidance and plan to update this page as we make progress on these milestones.

The table below provides a summary of the work required to ensure that applications using the Voice SDK are compatible with iOS 14.

Milestone | Timeline | Developer Actions
-- | -- | --
iOS 14 - beta 2 | July 7th, 2020 |  
Validate SDK compatibility with apps running on iOS 14 but do not target iOS 14. Specifically, ensure that SDKs and apps comply with behavior changes to all apps. | July 27 | Monitor this page for SDK and app releases compatible with iOS 14.Validate your applications with SDK releases compatible with iOS 14 to check our work. Please note that these SDK releases are not guaranteed to work on apps that already target iOS 14.(Optional) For apps not targeting iOS 14, developers can publish a new version of their application with an SDK release compatible with iOS 14
iOS 14 - beta 3 | July 22nd, 2020 |  
Validate SDK compatibility with apps running on iOS 14 but do not target iOS 14. Specifically, ensure that SDKs and apps comply with behavior changes to all apps. | Early August | Monitor this page for SDK and app releases compatible with iOS 14.Validate your applications with SDK releases compatible with iOS 14 to check our work. Please note that these SDK releases are not guaranteed to work on apps that already target iOS 14.(Optional) For apps not targeting iOS 14, developers can publish a new version of their application with an SDK release compatible with iOS 14
iOS 14 | September 16th, 2020 | iOS 14 was released by Apple. Voice iOS SDK 2.1.0-2.1.1 and 5.0.0+ are fully compatible with iOS 14.

### CallKit and PushKit

iOS 14 has no API updates that impact usage of the Voice iOS SDK. The following are the updates that we are aware of  -

1. iOS 13 mandated reporting an incoming push notification to CallKit via `reportNewIncomingCallWithUUID` API, however you could still ignore an incoming push notification by supplying a  `nil` UUID to `reportNewIncomingCallWithUUID` API. 

    But in iOS 14, when a `nil` UUID is passed to `reportNewIncomingCallWithUUID`, iOS will kill your app with following error reported on console - 

```log
    2020-07-15 20:13:37.488273-0700 ProgrammableVoiceTestapp[4708:451671] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CXProvider reportNewIncomingCallWithUUID:update:completion:]: parameter 'UUID' cannot be nil'
    *** First throw call stack:
    (0x1b2bed80c 0x1b2915fa4 0x1b2ae2f84 0x1c0910edc 0x1020ffc10 0x1020ff474 0x10266ef50 0x1039188d0 0x102667a10 0x1020ff1ac 0x1c686f8ec 0x1021ed7fc 0x1021eebd8 0x1021fcc34 0x1b2b6b3a8 0x1b2b6639c 0x1b2b658a0 0x1bcabb328 0x1b6c55988 0x10210c7a8 0x1b29f0360)
    libc++abi.dylib: terminating with uncaught exception of type NSException
```

2. If your app uses the Voice iOS SDK 4.x version or below, iOS 14 may not terminate your app in a race condition if cancel push notification is received before CallKit could call the completion handler for `reportNewIncomingCallWithUUID` is called. However we strongly recommend using our latest 5.x SDK to support Apple’s CallKit and PushKit integration requirements.

### App Clips

The Voice iOS SDK requires socket connections to establish both the signaling and media connection for calls, but currently it is not supported in App Clip apps so applications won't be able to make or accept calls using the SDK.

Please see https://developer.apple.com/forums/thread/652104 for future compatibility updates.

That being said, PushKit is still supported in App Clip apps. Use a separate certificate signing request file and generate a separate VoIP Service certificate with the bundle ID (`com.main.bundleid.Clip`) for your App Clip extension apps.

Please note that applications need to use the Apple Developer Program account in order to create bundle certificate for App Clip apps, which is not supported with the Enterprise account. Please see https://developer.apple.com/forums/thread/654943.

**Comment by idelgado** [comment]
iOS 14 was released by Apple on September 16th, 2020.

**Voice iOS SDK 2.1.0-2.1.1** and **5.0.0+** are fully compatible with iOS 14.
