### ISSUE TITLE
Ending a call before connected won't cancel and send correct webhook

### ISSUE THREAD

**Issue by majum** [twilio/twilio-voice-ios#6]
### Description

I use [voice conference](https://www.twilio.com/voice/conference).

Hanging up a call before it is connected does not actually hang. The reason behind is that I am actually unable to hang up the call because call (`TVOCall`) object has not been initialized yet, so, calling `call?.disconnect()` has no effect where `call` object is nil. I can't find any other method to tell `Twilio iOS SDK` to close the connection (force close) it makes to whatever server.

I get webhook after the operator speaking** ends, so hanging before that speaking completes could be the reason of not getting related webhook but I still believe I should be getting "conference-end" webhook. I get `direction: inbound` webhook as if I never canceled the call.

** _Thank you for using your demo account. Please upgrade to a full account to remove this message_

### Steps to Reproduce

1. Start the call (in my case, it is by calling `performStartCallAction(callId: UUID, handle: String)` which requests `CXStartCallAction` from `CXCallController`)
2. Hang up the call by UI (tapping on a button or something) as fast/soon as possible (in my case, it is by calling `performEndCallAction(uuid: UUID)` which requests `CXEndCallAction` from `CXCallController`)
3. Now you should be getting call invite on the callee side. Even worse, webhook server won't get "conference-end" webhook from Twilio.

#### Expected Behavior

Not getting a call invite on callee side (since it is canceled) and getting a "participant-leave" or "conference-end" (this makes more sense as nobody left in the conference) webhook.

#### Actual Behavior

Callee gets call invite in pending (`TVOCallInviteStatePending`) state. My server is not getting a "conference-end" or "participant-leave" webhook in a such case.

#### Reproduces How Often

That error/bug occurs all the time, there is no specific configuration as long as you hang up the call as fast as possible (before the call object initialized).

#### Voice iOS SDK

The latest SDK which is 2.0.7 (from `TwilioVoice.version()`)

#### Xcode

Version 10.1

#### iOS Version

Version 10 and above

#### iOS Device

iPhone 5, iPhone 5S and iPhone 6

**Comment by bchen-twilio** [comment]
Hi @majum 

Sorry for my delay of getting back to you.
`TwilioVoice.call()` should return a non-nil `TVOCall` object and you can use the object to disconnect the call.

-bobie
