### ISSUE TITLE
Incorrect version in the info.plist file of XCFramework

### ISSUE THREAD

**Issue by jasdeepsaini** [twilio/twilio-voice-ios#71]
### Description

While manually adding `TwilioVoice.xcframework`, I checked the info.plist file to make sure I have the correct version of the framework.  The version in the info.plist is 1.0 instead of 6.2.1.

### Steps to Reproduce

1. Download `TwilioVoice.xcframework` for v6.2.0 or v6.2.1.
2. Navigate to the `info.plist` file in either architecture.
    - `TwilioVoice.xcframework/ios-x86_64-simulator/TwilioVoice.framework` 
    - `TwilioVoice.xcframework/ios-arm64/TwilioVoice.framework`
3. The value for `Bundle version string (short)` should be 6.2.1

#### Voice iOS SDK

6.2.0 and 6.2.1 XCFrameworks

**Comment by bobiechen-twilio** [comment]
Thanks for reporting the issue @jasdeepsaini. I have created a ticket for tracking the bug and will provide an update when this is fixed.

Cheers,
bobie

**Comment by bobiechen-twilio** [comment]
Hi @jasdeepsaini 

We have released the [Voice iOS SDK 6.2.2](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#622) which includes the fix of the version number in the framework plist. Thanks again for reporting this one.

Best,
-bobie
