### ISSUE TITLE
New Issue template links to Video Guides instead of Voice Guides

### ISSUE THREAD

**Issue by danhd123** [twilio/twilio-voice-ios#73]
### Description

New Issue template links to Video Guides instead of Voice Guides. 

### Steps to Reproduce

1. Go to https://github.com/twilio/twilio-voice-ios/issues/new
2. Observe the new issue template.
3. Read the "Before filing an issue please check the the issue is not already addressed by the following:" section

#### Expected Behavior

The "Voice Guides" line should link to the Voice Guides

#### Actual Behavior

The "Voice Guides" line links to the Video Guides

#### Reproduces How Often

100%
### Versions

3/26/2021 at 10:30 PM PST

**Comment by bobiechen-twilio** [comment]
Thank you so much for reporting this one @danhd123. Fixed in #74.
