### ISSUE TITLE
Carthage + xcframework

### ISSUE THREAD

**Issue by marcelofabri** [twilio/twilio-voice-ios#78]
### Description

The SDK is now distributed as an xcframework, and due to that, Carthage support was paused. However,  [Carthage 0.38.0](https://github.com/Carthage/Carthage/releases/tag/0.38.0) supports binary xcframeworks.

### Steps to Reproduce

1. Open https://github.com/twilio/twilio-voice-ios/blob/Releases/twilio-voice-ios.json
2. Check for an xcframework in the format that Carthage expects

#### Expected Behavior

An xcframework to be present

#### Actual Behavior

Only .frameworks are in the JSON

#### Reproduces How Often

Always

**Comment by bobiechen-twilio** [comment]
Hi @marcelofabri,

Thanks for reaching and I feel terrible to not have responded back sooner.
Carthage + XCFramework support has been reenabled in #79.

**Comment by marcelofabri** [comment]
Thanks @bobiechen-twilio! Any chance we can add it back to https://github.com/twilio/twilio-chat-ios as well? Should I create an issue in that repo?

**Comment by bobiechen-twilio** [comment]
Sure thing @marcelofabri! Let's create a ticket in the project so the team can track the progress. 👍

**Comment by marcelofabri** [comment]
Done: https://github.com/twilio/twilio-chat-ios/issues/32
