### ISSUE TITLE
Can't get voice when iPhone using VPN software(Outline)

### ISSUE THREAD

**Issue by weitsungchengkkday** [twilio/twilio-voice-ios#80]
### Description
When Client User is using  VPN software(Outline) , can not get voice from a incoming call

### Steps to Reproduce

make a call from A Client to B Client

#### Error Message from iOS APP

```swift
Error Domain=com.twilo.voice.error Code=53405 \"Media connection failed\" UserInfo={NSLocalizedDescription=Media connection failed, NSLocalizedFailureReason=Media disconnected due to ICE failure.}"
```

#### Expected Behavior

hear voice 

#### Actual Behavior

only get signal, with no voice

#### Reproduces How Often

[What percentage of the time does it reproduce?]
Always
#### Logs

```
Call log: https://console.twilio.com/us1/monitor/logs/calls?frameUrl=%2Fconsole%2Fvoice%2Fcalls%2Flogs%2FCA7332f4c2128305ee7d3e8f95a67008e9%3F__override_layout__%3Dembed%26x-target-region%3Dus1
```

#### Voice iOS SDK
6.3.0 via CocoaPods

#### Xcode
12.5

#### iOS Version
14.5 (had applied new iOS 14 Privacy Policy)

#### iOS Device
iphone 12

###  perfrom call & answer call 
```swift
 
    func performVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Void) {
        
        guard let identity = identity, let url = accessTokenURL else {
            return
        }
        
        fetchAccessToken(url: url, identity: identity) { [weak self] accessToken in
            guard let accessToken = accessToken,
                  let weakSelf = self,
                  let params = weakSelf.callInfo?.dictionary else {
                completionHandler(false)
                return
            }
            
            let options = ConnectOptions(accessToken: accessToken) { builder in
                builder.params = params
                builder.uuid = uuid
            }
            
            // Call Delegate
            weakSelf.activeCall = TwilioVoiceSDK.connect(options: options, delegate: weakSelf)
            
            weakSelf.callKitCompletionCallback = completionHandler
        }
        
    }
    
    func performAnswerVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Void) {
        
        guard let invite = activeCallInvites[uuid.uuidString] else {
            return
        }
        
        let acceptOptions = AcceptOptions(callInvite: invite) { builder in
            builder.uuid = invite.uuid
        }
        
        let call = invite.accept(options: acceptOptions, delegate: self)
        
        activeCall = call
        guard let uuid = call.uuid else { return }
        activeCalls[uuid.uuidString] = call
        callKitCompletionCallback = completionHandler
        activeCallInvites.removeValue(forKey: uuid.uuidString)
    }
```
###

**Comment by bobiechen-twilio** [comment]
Hi @weitsungchengkkday 

Thanks for the error message and code snippet. It looks like the ICE candidate negotiation failed which led to the media connection failure, and the restricted network could very likely be the reason. 
In case VPN is required for the device while connecting the SDK call and it might provide restricted network access, you can use the [Twilio Network Traversal Service](https://www.twilio.com/docs/stun-turn/api) to construct the ICE options object for the TVOConnectOptions/TVOAcceptOptions:

```
    // fetching and constructing TVOIceOptions
    TVOIceOptions *iceOptions = ...

    TVOConnectOptions *connectOptions = [TVOConnectOptions optionsWithAccessToken:self.accessToken
                                                                            block:^(TVOConnectOptionsBuilder *builder) {
        builder.iceOptions = iceOptions;
    }];

    TVOCall *call = [TwilioVoiceSDK connectWithOptions:connectOptions delegate:self];
```

You can check out the example code of how to initialize the `TVOIceOptions` object using the response from the Twilio Network Traversal in this thread: https://github.com/twilio/twilio-voice-ios/issues/14

**Comment by weitsungchengkkday** [comment]
Thanks You! @bobiechen-twilio 
As you mention above we can add iceOption for restricted network, about these I wonder 
1.  if I use old code as I mentioned about  above (without iceOption), does it means no ice server will be used?
2. if I use  ice server Twilio provide, does it means extra fee would be produced for per Call
 
3. More,  we also use website to get Twilio Voice Call as Client side in same VPN Environment. But website does not meet same problem, quite strange.

**Comment by weitsungchengkkday** [comment]
Thank @bobiechen-twilio  
I tried suggestion using ice server, that works! (I modify the code as below)

But I still wonder above three question. Pls help, thanks you.

```swift
    func performVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Void) {
        
        guard let identity = identity, let url = accessTokenURL else {
            return
        }
        
        fetchAccessToken(url: url, identity: identity) { [weak self] accessToken in
            guard let accessToken = accessToken,
                  let weakSelf = self,
                  let params = weakSelf.callInfo?.dictionary else {
                completionHandler(false)
                return
            }
            
            let iceOptions: IceOptions = IceOptions { builder in
                builder.servers = self?.iceServers
            }
            
            let options = ConnectOptions(accessToken: accessToken) { builder in
                
                builder.params = params
                builder.uuid = uuid
                builder.iceOptions = iceOptions
            }
            
            // Call Delegate
            weakSelf.activeCall = TwilioVoiceSDK.connect(options: options, delegate: weakSelf)
            
            weakSelf.callKitCompletionCallback = completionHandler
        }
        
    }
    
    func performAnswerVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Void) {
        
        guard let invite = activeCallInvites[uuid.uuidString] else {
            return
        }
        
        let iceOptions: IceOptions = IceOptions { builder in
            builder.servers = self.iceServers
        }
        
        let acceptOptions = AcceptOptions(callInvite: invite) { builder in
            
            builder.uuid = invite.uuid
            builder.iceOptions = iceOptions
        }
        
        let call = invite.accept(options: acceptOptions, delegate: self)
        
        activeCall = call
        guard let uuid = call.uuid else { return }
        activeCalls[uuid.uuidString] = call
        callKitCompletionCallback = completionHandler
        activeCallInvites.removeValue(forKey: uuid.uuidString)
    }
```

**Comment by bobiechen-twilio** [comment]
Glad that the ICE options solved the issue @weitsungchengkkday.

> we also use website to get Twilio Voice Call as Client side in same VPN Environment. But website does not meet same problem, quite strange.

The Twilio Voice iOS SDK and the JS SDK talk to different Twilio Voice endpoints with different protocols.

> if I use ice server Twilio provide, does it means extra fee would be produced for per Call

Yes, the Network Traversal Service that provides the ICE servers is a separate Twilio service. Using the service will require additional fee other than the Voice call minutes.

> if I use old code as I mentioned about above (without iceOption), does it means no ice server will be used?

The Voice iOS SDK actually uses a default Twilio STUN server if none is provided in the connect/accept options from the application. We have a theory that the network environment of the VPN used on the device might be blocking the port used by the default server (`stun:global.stun.twilio.com:3478?transport=udp`). One thing you can try instead of ICE options is enabling the `enableIceGatheringOnAnyAddressPorts` flag of the connect/accept options: [API doc](https://twilio.github.io/twilio-voice-ios/docs/latest/Classes/TVOCallOptions.html#//api/name/enableIceGatheringOnAnyAddressPorts).
This could potentially increase the time of ICE candidate gathering thus slightly longer time to connect a call but should hopefully resolve the situation of restricted network environment.

Let me know if this helps.

**Comment by weitsungchengkkday** [comment]
Thank you @bobiechen-twilio 
I tried your suggestion turn on the enableIceGatheringOnAnyAddressPorts as  below

**Comment by weitsungchengkkday** [comment]
Thank you @bobiechen-twilio 
I tried your suggestion turn on the enableIceGatheringOnAnyAddressPorts (but not provide iceOption) as below. Unfortunately, it does not work.

I wonder that 
1. Does turn on enableIceGatheringOnAnyAddressPorts means using ice server? (even though iceOption is not provided), 
2. Does turn on enableIceGatheringOnAnyAddressPort can get more ice candidates? (default only get  candidates on 3478  port? )

```swift
    
    func performVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Void) {
        
        if let url = self.iceServersURL {
            fetchIceServers(url: url) { [weak self] iceServers in
                
                guard let weakSelf = self else {
                    return
                }
                
                guard let identity = weakSelf.identity, let url = weakSelf.accessTokenURL else {
                    return
                }
                
                weakSelf.fetchAccessToken(url: url, identity: identity) { [weak self] accessToken in
                    guard let accessToken = accessToken,
                          let weakSelf = self,
                          let params = weakSelf.callInfo?.dictionary else {
                        completionHandler(false)
                        return
                    }
                    
                    let iceOptions: IceOptions = IceOptions { builder in
                        builder.servers = iceServers
                    }
                    
                    let options = ConnectOptions(accessToken: accessToken) { builder in
                      
                        builder.params = params
                        builder.uuid = uuid
                        builder.enableIceGatheringOnAnyAddressPorts = true
                     //   builder.iceOptions = iceOptions
                    }
                    
                    // Call Delegate
                    weakSelf.activeCall = TwilioVoiceSDK.connect(options: options, delegate: weakSelf)
                    
                    weakSelf.callKitCompletionCallback = completionHandler
                }
                
            }
        }
        
    }
    
    func performAnswerVoiceCall(uuid: UUID, completionHandler: @escaping (Bool) -> Void) {
        
        if let url = self.iceServersURL {
            fetchIceServers(url: url) { [weak self] iceServers in
                
                guard let weakSelf = self else {
                    return
                }
                
                guard let invite = self?.activeCallInvites[uuid.uuidString] else {
                    return
                }
                
                let iceOptions: IceOptions = IceOptions { builder in
                    builder.servers = iceServers
                
                }
                
                let options = AcceptOptions(callInvite: invite) { builder in
                    builder.enableIceGatheringOnAnyAddressPorts = true
                    builder.uuid = invite.uuid
                        //  builder.iceOptions = iceOptions
                }
                
                let call = invite.accept(options: options, delegate: weakSelf)
                
                weakSelf.activeCall = call
                guard let uuid = call.uuid else { return }
                weakSelf.activeCalls[uuid.uuidString] = call
                self?.callKitCompletionCallback = completionHandler
                weakSelf.activeCallInvites.removeValue(forKey: uuid.uuidString)
                
            }
        }
        
    }
```

**Comment by bobiechen-twilio** [comment]
Hi @weitsungchengkkday 

Sorry that I couldn't get back to you sooner.
Thanks for the update. It does seem that ICE options is the only solution in this environment.

Question - is the restricted network environment (VPN) a requirement for the app that you are working on, or is it only for the dev device?

**Comment by weitsungchengkkday** [comment]
Hi @bobiechen-twilio 
I appreciate your help very much

VPN environment is necessary, because iOS APP need to get essential config file when user login. 
Unless user need to turn off the VPN after they login. 

I tried only use specific TURN Server as iceOption. I found  UDP protocol TURN server does not work (turn:global.turn.twilio.com:3478?transport=udp),  but other two TCP protocol TURN server work (turn:global.turn.twilio.com:3478?transport=tcp, turn:global.turn.twilio.com:443?transport=tcp).

I also wonder that
Does turn on enableIceGatheringOnAnyAddressPorts means using ice server? (even though iceOption is not provided),
Does turn on enableIceGatheringOnAnyAddressPort can get more ice candidates? (default only get candidates on 3478 port?)

**Comment by bobiechen-twilio** [comment]
Hi @weitsungchengkkday 

Apology that I couldn't get back to you sooner.

The SDK uses a default STUN server if none is provided, with or without enabling the `enableIceGatheringOnAnyAddressPorts` flag. When the flag is enabled, the SDK will use some of the "any address" type of network interfaces if others failed the ICE negotiation. In your case unfortunately the SDK was not able to get through the VPN without the additional ICE Servers.

Let me check with our STUN/TURN experts and get back to you.

**Comment by weitsungchengkkday** [comment]
Thanks @bobiechen-twilio   
We use ICE server as  temporary action by now. 
And wait for your further info. Thanks you bobie
