### ISSUE TITLE
call.disconnect() is not executed when app is terminated.

### ISSUE THREAD

**Issue by SushanDristi** [twilio/twilio-voice-ios#87]
Description
When app is terminated, I want to disconnect the call.  I tried to use applicationWillTerminate() to disconnect the call but disconnect() is not executed.

Steps to Reproduce
Using the sample app

call a phone number
wait for the phone to ring
answer the call 
kill the app
==>call is not ended on other side

Code

    override func applicationWillTerminate(_ application: UIApplication) {
     self.performEndCallAction(callUuid: call.uuid, phoneNumber: self.calleePhoneNumber ?? "NO PHONE #???")
    call.disconnect()
    }

Expected Behavior
The rest call should be performed from the SDK to disconnect the call

Actual Behavior
disconnect method is not executed.

Reproduces How Often
100%

Versions
All relevant version information for the issue.

Voice iOS SDK
6.x 

Xcode
 14.4

iOS Version
12.4.1

iOS Device
iPhone *

**Comment by bobiechen-twilio** [comment]
Hi @SushanDristi 

The `.disconnect()` method requires a few handshaking steps between the mobile client and the service, which cannot be completed with the time given by the `applicationWillTerminate()` callback. This is currently a known issue/behavior of the SDK.

Sorry for the inconvenience.

**Comment by SushanDristi** [comment]
@bobiechen-twilio 
If a user terminated the iOS app, the call is ended on that user app, but the user on the other side of the call is still active. Is there any workaround for this issue?

**Comment by bobiechen-twilio** [comment]
Hi @SushanDristi 

The Voice service has a timer to detect and kill a call if the no audio packets (silence) are received from the client for one minute. In this case even though the mobile client is not able to complete the disconnect process, the call will still end after a minute in case no user action.
