### ISSUE TITLE
DTMF tones are not audible from the user who sends them

### ISSUE THREAD

**Issue by gianpispi** [twilio/twilio-voice-ios#91]
Hi everyone!

### Description

We have two iOS apps that use the last version of Twilio Voice (6.3.1). When sending digits, the receiver can hear them, but not the user who sends them.

We have an old version of one of these two apps that integrates the 6.0.2 SDK, and there it works as intended, where both sides can hear the tones.

### Steps to Reproduce

1. Start a call
2. Send a digit via `sendDigits(_:)`
3. Nothing audible

#### Code

```swift
call.sendDigits("3")
```

#### Expected Behavior

Both sides can hear the DTMF tones

#### Actual Behavior

The sender cannot hear the DTMF tones; only the receiver can.

#### Reproduces How Often

Always

### Versions

I tested 6.3.1, 6.2.0

#### Voice iOS SDK

6.3.1 via SPM

#### Xcode

13.2.1

#### iOS Version

15.4

#### iOS Device

Generic iOS device

**Comment by bobiechen-twilio** [comment]
Hi @gianpispi 

The Voice SDK does not play DTMF tones for the local client. To workaround this, you can use the playback frameworks such as AVAudioPlayer to play tone files in the app at the same time when calling `sendDigits()`.

**Comment by ream88** [comment]
@bobiechen-twilio it did this in the past, right? Could playing it locally via AVAudioPlayer lead to sending the DTMF tones multiple times? Because the microphone listens to it, as its played via AVAudioPlayer and therefore the other side hears it a second time?
