### ISSUE TITLE
Add support for Apple's native noise cancellation (aka voice isolation)

### ISSUE THREAD

**Issue by nalexn** [twilio/twilio-voice-ios#93]
### This is a feature request

Are there any plans on adding support for Apple's programmatic noise cancellation? It is actually available to third-party apps starting from iOS 15: Snapchat, WhatsApp, Slack, Signal, and Instagram are [already using it](https://www.theverge.com/23123578/apple-voice-isolation-facetime-calls).

As [WWDC 2021](https://developer.apple.com/videos/play/wwdc2021/10047/?time=1384) video says, we need to properly configure the [Audio Unit Voice IO](https://developer.apple.com/documentation/audiotoolbox/audio_unit_voice_i_o) (or AUVoiceIO).

[AVCaptureDevice.MicrophoneMode.voiceIsolation](https://developer.apple.com/documentation/avfoundation/avcapturedevice/microphonemode/voiceisolation), for example, is the audio mode that applies the most aggressive noise cancellation and works phenomenally well.

The mode itself can only be toggled by the user in the Control center, however, in order for this setting to appear there, Twilio SDK has to correctly configure the `AUVoiceIO`

**Comment by bobiechen-twilio** [comment]
Hi @nalexn 

Thanks for reaching out. I have a created a ticket and we will keep this one in our radar.

-bobie

**Comment by servercimen** [comment]
@bobiechen-twilio I see the feature request is closed. Is there any documentation about if and how Twilio voice SDK uses [Audio Unit Voice IO](https://developer.apple.com/documentation/audiotoolbox/audio_unit_voice_i_o)?

I see this [audio device example](https://github.com/twilio/voice-quickstart-ios/tree/master/AudioDeviceExample) from a while ago. Can you confirm this is no longer needed to use Audio Unit Voice IO with Twilio?
